version: "3.0"
services:
  database-postgres:
    container_name: postgres
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user_blog
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: test_blog
    restart: always
  database-postgres-test:
    container_name: postgres-test
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: test_user
      POSTGRES_DB: database_test
      POSTGRES_PASSWORD: pwd
    restart: always
  database-mongo:
    container_name: mongo
    image: mongo
    ports:
      - "8081:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
  database-mongo-test:
    container_name: mongo-test
    image: mongo
    ports:
      - "8082:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
