version: "3.0"
services:
  database:
    container_name: postgres
    image: postgres
    ports:
      - "5437:5432"
    environment:
      POSTGRES_USER: user_blog
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: test_blog
    restart: always
  database-test-latest:
    container_name: postgres-test-last
    image: postgres
    ports:
      - "5438:5432"
    environment:
      POSTGRES_USER: test_user
      POSTGRES_DB: database_test
      POSTGRES_PASSWORD: pwd
    restart: always